default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cms_rails_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: cms_rails_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: cms_rails_production
  username: cms_rails
  password: <%= ENV["CMS_RAILS_DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>